openapi: 3.0.0
x-samples-languages:
  - java
info:
  description: Customers service for WFIiS AGH game shop project
  version: 1.0.0
  title: Customers Service
paths:
  /:
    get:
      tags:
        - Customers
      description: Get all customers
      operationId: getAllCustomers
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Authorization token
      responses:
        "200":
          description: Returns list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDto"
    put:
      tags:
        - Customers
      description: Update customer
      operationId: updateCustomer
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Authorization token
      requestBody:
        description: Customer with updated values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDto'
      responses:
        "200":
          description: Returns updated customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"

  /{id}:
    get:
      tags:
        - Customers
      description: Get customer by id
      operationId: getCustomerById
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Authorization token
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Customer id
      responses:
        "200":
          description: Returns specific customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
    delete:
      tags:
        - Customers
      description: Delete customer by id
      operationId: deleteCustomerById
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Authorization token
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Customer id
      responses:
        "200":
          description: Specific customer deleted
  /auth:
    post:
      tags:
        - CustomersAuth
      description: Creates new customer
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRegistrationDto"
        required: true
      responses:
        "200":
          description: Returns created customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
    get:
      tags:
        - CustomersAuth
      description: Gets customer by mail and password
      operationId: getAuthCustomer
      parameters:
        - in: query
          name: mail
          schema:
            type: string
        - in: query
          name: password
          schema:
            type: string
      responses:
        "200":
          description: Returns customer by mail and password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"

components:
  schemas:

    UserType:
      type: string
      enum:
        - Customer
        - Staff

    CustomerDto:
      description: Keeps information about customer
      type: object
      properties:
        id:
          type: integer
        mail:
          type: string
        userType:
          $ref: '#/components/schemas/UserType'
      required:
        - id
        - mail
        - userType

    CustomerRegistrationDto:
      description: Keeps information about new customer
      type: object
      properties:
        mail:
          type: string
        password:
          type: string
        userType:
          $ref: '#/components/schemas/UserType'
      required:
        - mail
        - password
        - userType