openapi: 3.0.0
x-samples-languages:
  - java
info:
  description: Authentication service for WFIiS AGH game shop project
  version: 1.0.0
  title: Authentication Service
tags:
  - authentication
paths:
  /authenticate:
    post:
      tags:
        - authentication
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
components:
  schemas:
    AuthenticationRequest:
      type: object
      description: authentication request
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password
    AuthenticationResponse:
      type: object
      description: authentication response
      properties:
        token:
          type: string
          description: jwt token