export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const CHECK_USER_TOKEN_REQUEST = "CHECK_USER_TOKEN_REQUEST";
export const CHECK_USER_TOKEN_SUCCESS = "CHECK_USER_TOKEN_SUCCESS";
export const CHECK_USER_TOKEN_FAILURE = "CHECK_USER_TOKEN_FAILURE";
